#define led PORTA.RA0      // ÝSTERSEK ATABÝLÝRÝZDE AÞAÐIDAKÝ YERE " led " yazabiliriz.



void main() {
// TRISA=0;//PORTA  DECÝMAL(10'LUK) SÝSTEMDE TAMAMEN ÇIKIÞ YAPTIK
TRISA=0B00000000; // PORTA BINARY(2LÝK) SÝSTEMDE ÇIKIÞ YAPILDI - EGER BINARY VERÝCEKSEK 0B YAZILMASI LAZIM
// TRISA=0X00 ; // PORTA HEXADECÝMAL SÝSTEMDE ÇIKIÞ YAPILDI 0X HEXADECÝMAL

PORTA=0; // PORTA ÝÇERÝÐÝ TEMÝZLENDÝ

while(1) // sonsuz döngü yada for(;;) bu komut ilede yapabiliriz.
{
PORTA.RA0=1;    // PORTA'NIN 0.CI BACAÐINI 1 YAP YANÝ 17.BACAGINA +5V YOLLADIK
DELAY_MS(1000);
PORTA.RA0=0; // PORTA'NIN 0.CI BÝTÝNÝ 0 YAPTIK 17.BACAGI 0 VOLT YOLLADIK
DELAY_MS(1000);


}

}